# Major investor markets that get their own page under /locations/<state>/<metro>/ (only when the state is served).
# 'angle' is the market-specific paragraph. Keep it qualitative and true; never invent statistics.
$Metros = @(
  @{ slug="atlanta"; name="Atlanta"; abbr="GA"; programs="rental and renovation"; angle="Metro Atlanta is one of the most active investor markets in the Southeast, with a deep supply of single-family homes in the surrounding suburbs and a steady flow of renovation projects inside the perimeter. Investors here use short-term loans to buy and renovate, then refinance the finished properties into long-term rental financing." }
  @{ slug="tampa"; name="Tampa"; abbr="FL"; programs="rental and renovation"; angle="The Tampa Bay area combines strong rental demand with older housing stock that rewards renovation. Insurance and flood-zone considerations vary a lot by neighborhood and can change how a rental pencils out, so running the full payment early matters." }
  @{ slug="orlando"; name="Orlando"; abbr="FL"; programs="rental and short-term rental"; angle="Orlando's tourism-driven economy supports both traditional rentals and short-term rental strategies, and its steady growth keeps renovation and new construction active. Always confirm local short-term rental rules before you underwrite a deal around them." }
  @{ slug="jacksonville"; name="Jacksonville"; abbr="FL"; programs="rental and flip"; angle="Jacksonville offers a wide range of price points across a large geographic area, which makes it popular with investors buying single-family rentals and renovating older homes." }
  @{ slug="miami"; name="Miami"; abbr="FL"; programs="multifamily and renovation"; angle="Miami and surrounding South Florida markets are high-value, and small multifamily and condo-heavy submarkets each have their own rules. Condo and association details can affect financing, so we look at each property individually." }
  @{ slug="houston"; name="Houston"; abbr="TX"; programs="rental and flip"; angle="Houston's size and diverse neighborhoods give investors a wide range of price points for rentals and flips. Property taxes are a meaningful part of the payment, so a DSCR calculation should always include them." }
  @{ slug="dallas"; name="Dallas"; abbr="TX"; programs="rental, flip and new construction"; angle="Dallas-Fort Worth continues to attract rental investors, builders and flippers, with new construction active throughout the metro. High property taxes make full-payment math important on rentals." }
  @{ slug="san-antonio"; name="San Antonio"; abbr="TX"; programs="rental and flip"; angle="San Antonio offers approachable price points and steady rental demand, with older neighborhoods that often suit renovation strategies." }
  @{ slug="austin"; name="Austin"; abbr="TX"; programs="flip and new construction"; angle="Austin's higher prices and strong demand make the numbers on a flip or build especially sensitive to the after-repair value and holding time, so careful underwriting of both is key." }
  @{ slug="charlotte"; name="Charlotte"; abbr="NC"; programs="rental and renovation"; angle="Charlotte's steady population growth supports rental demand across the city and its suburbs, and its mix of older and newer housing creates opportunities for both renovation and buy-and-hold investors." }
  @{ slug="raleigh"; name="Raleigh"; abbr="NC"; programs="rental and new construction"; angle="The Raleigh-Durham area has a strong employment base and active new construction, which brings builders and rental investors into the same market." }
  @{ slug="nashville"; name="Nashville"; abbr="TN"; programs="flip and rental"; angle="Nashville's growth has pushed prices up in many neighborhoods, so flip and ground-up deals depend on a realistic after-repair value. Rentals can still work in the surrounding suburbs, where price points differ." }
  @{ slug="memphis"; name="Memphis"; abbr="TN"; programs="rental"; angle="Memphis has long been a destination for cash-flow-focused rental investors, thanks to modest purchase prices relative to rents. Condition, tenant quality and insurance costs are the details to check closely." }
  @{ slug="phoenix"; name="Phoenix"; abbr="AZ"; programs="rental and flip"; angle="Phoenix and its fast-growing suburbs have supported both single-family rentals and renovation projects, with a wide spread of price points across the valley." }
  @{ slug="baltimore"; name="Baltimore"; abbr="MD"; programs="rental and renovation"; angle="Baltimore has a large stock of older row homes and small multifamily buildings, which makes it popular with renovation and rental investors. Terms vary by neighborhood and property, so we confirm each deal individually." }
  @{ slug="philadelphia"; name="Philadelphia"; abbr="PA"; programs="renovation and multifamily"; angle="Philadelphia's dense neighborhoods of row homes and small multifamily buildings give investors plenty of renovation and rental opportunities, with conditions that vary block by block." }
  @{ slug="pittsburgh"; name="Pittsburgh"; abbr="PA"; programs="rental and renovation"; angle="Pittsburgh's older housing stock and moderate prices make it a favorite for investors who want to renovate and hold, with rents that can support the payment on many properties." }
  @{ slug="columbus"; name="Columbus"; abbr="OH"; programs="rental and flip"; angle="Columbus pairs a growing economy with approachable price points, giving investors both rental and flip options across the city and its suburbs." }
  @{ slug="cleveland"; name="Cleveland"; abbr="OH"; programs="rental"; angle="Cleveland is known for low purchase prices relative to rents, which attracts cash-flow investors. Property condition and neighborhood matter a great deal here, so inspections and realistic rehab budgets are essential." }
  @{ slug="cincinnati"; name="Cincinnati"; abbr="OH"; programs="rental and renovation"; angle="Cincinnati offers older housing stock, moderate prices and steady rental demand, with a mix of single-family and small multifamily properties." }
  @{ slug="indianapolis"; name="Indianapolis"; abbr="IN"; programs="rental and flip"; angle="Indianapolis has long been popular with Midwest cash-flow investors, with modest prices and a broad rental market, plus ongoing opportunities for renovation." }
  @{ slug="chicago"; name="Chicago"; abbr="IL"; programs="multifamily and renovation"; angle="Chicago's two- to four-flat buildings are a staple of the investor market, with values and rents that vary widely between neighborhoods. Taxes and building condition are important parts of the numbers." }
  @{ slug="detroit"; name="Detroit"; abbr="MI"; programs="rental and renovation"; angle="Detroit offers low entry prices and strong renovation activity, which can produce attractive returns for investors who budget carefully for rehab and understand each neighborhood." }
  @{ slug="birmingham"; name="Birmingham"; abbr="AL"; programs="rental and flip"; angle="Birmingham's moderate prices and steady demand give investors rental and flip options, with a variety of neighborhoods and property conditions." }
  @{ slug="kansas-city"; name="Kansas City"; abbr="MO"; programs="rental and flip"; angle="Kansas City straddles two states and offers investors a broad range of price points across older city neighborhoods and newer suburbs." }
  @{ slug="st-louis"; name="St. Louis"; abbr="MO"; programs="rental and renovation"; angle="St. Louis has older housing stock, modest prices and a broad rental market, so many investors focus on renovation and cash flow." }
  @{ slug="denver"; name="Denver"; abbr="CO"; programs="flip and rental"; angle="Denver's higher prices make precise numbers essential on both flips and rentals, and its strong demand supports renovation projects and rentals in the right neighborhoods." }
  @{ slug="charleston"; name="Charleston"; abbr="SC"; programs="rental and short-term rental"; angle="Charleston combines year-round rental demand with a strong visitor economy, and older homes in the historic areas bring added renovation and zoning considerations that are worth checking early." }
  @{ slug="louisville"; name="Louisville"; abbr="KY"; programs="rental and renovation"; angle="Louisville offers moderate prices and steady rental demand, with older neighborhoods that suit renovation strategies." }
  @{ slug="milwaukee"; name="Milwaukee"; abbr="WI"; programs="multifamily and rental"; angle="Milwaukee's many two- to four-unit buildings and moderate prices make it a classic market for investors building a small multifamily portfolio." }
  @{ slug="minneapolis"; name="Minneapolis"; abbr="MN"; programs="rental and renovation"; angle="The Twin Cities combine a strong employment base with a mix of older single-family and small multifamily properties that suit both renovation and long-term rental strategies." }
)
