# Single source of truth for state data. Used by gen-locations.ps1 and build-site.ps1.
# States we do not lend in live in tools/excluded-states.txt (space-separated abbreviations).
$AllStates = @(
  @{ slug="alabama"; name="Alabama"; abbr="AL"; metros="Birmingham, Huntsville, Mobile, Montgomery"; note="Alabama offers lower price points that can produce strong rent-to-price ratios, with Huntsville and Birmingham standing out for demand." }
  @{ slug="alaska"; name="Alaska"; abbr="AK"; metros="Anchorage, Fairbanks, Juneau, Wasilla"; note="Alaska is a smaller, more specialized market, with rental demand concentrated around Anchorage and the Mat-Su valley. Every property is looked at individually." }
  @{ slug="arizona"; name="Arizona"; abbr="AZ"; metros="Phoenix, Mesa, Tucson, Scottsdale, Chandler"; note="Arizona's fast-growing metros have supported both rental and renovation activity, with single-family rentals especially popular." }
  @{ slug="arkansas"; name="Arkansas"; abbr="AR"; metros="Little Rock, Fayetteville, Bentonville, Fort Smith, Jonesboro"; note="Northwest Arkansas has seen strong growth, and lower price points across the state can produce attractive rent-to-price ratios for rental investors." }
  @{ slug="california"; name="California"; abbr="CA"; metros="Los Angeles, San Diego, Sacramento, Fresno, Riverside, San Jose"; note="California's high property values make precise numbers important. Loan size, rent and taxes all move the result, so it pays to run the deal before you offer." }
  @{ slug="colorado"; name="Colorado"; abbr="CO"; metros="Denver, Colorado Springs, Aurora, Fort Collins, Pueblo"; note="Front Range growth has kept rental demand and renovation activity steady, with a mix of single-family, townhome and small multifamily opportunities." }
  @{ slug="connecticut"; name="Connecticut"; abbr="CT"; metros="Hartford, New Haven, Bridgeport, Stamford, Waterbury"; note="Connecticut has a deep supply of older 2-4 unit buildings, which makes for plenty of rental and renovation opportunities." }
  @{ slug="delaware"; name="Delaware"; abbr="DE"; metros="Wilmington, Dover, Newark, Rehoboth Beach"; note="Delaware pairs Wilmington-area rentals with beach-market properties, each with its own numbers." }
  @{ slug="washington-dc"; name="Washington, D.C."; abbr="DC"; metros="Washington, D.C., plus nearby Maryland and Virginia suburbs"; note="D.C. is a high-value market where 2-4 unit properties and renovation projects are common. Run the numbers carefully since prices and rents vary widely by neighborhood." }
  @{ slug="florida"; name="Florida"; abbr="FL"; metros="Tampa, Orlando, Jacksonville, Miami, Fort Lauderdale, Tallahassee, Pensacola"; note="Florida has one of the most active investor markets in the country, with strong long-term and short-term rental demand and a steady flow of renovation projects. Insurance costs can be a big factor in how a rental pencils out, which is exactly what a DSCR calculation captures." }
  @{ slug="georgia"; name="Georgia"; abbr="GA"; metros="Atlanta, Savannah, Augusta, Macon, Columbus"; note="Metro Atlanta and its surrounding suburbs have drawn investors for years thanks to steady rental demand and a deep supply of single-family and small multifamily properties." }
  @{ slug="hawaii"; name="Hawaii"; abbr="HI"; metros="Honolulu, Kailua, Kapolei, Hilo, Kahului"; note="Hawaii is a unique, high-value market. Properties are reviewed individually so we can tell you honestly what is possible." }
  @{ slug="idaho"; name="Idaho"; abbr="ID"; metros="Boise, Meridian, Nampa, Idaho Falls, Coeur d'Alene"; note="Idaho's growing metros, especially the Boise area, have attracted both rental investors and flippers." }
  @{ slug="illinois"; name="Illinois"; abbr="IL"; metros="Chicago, Rockford, Joliet, Aurora, Peoria"; note="Chicago-area two- to four-flats and Midwest price points give Illinois investors a wide range of rental and rehab deals." }
  @{ slug="indiana"; name="Indiana"; abbr="IN"; metros="Indianapolis, Fort Wayne, Evansville, South Bend, Gary"; note="Indiana is a long-time favorite for cash-flow investors thanks to modest purchase prices relative to rents." }
  @{ slug="iowa"; name="Iowa"; abbr="IA"; metros="Des Moines, Cedar Rapids, Davenport, Iowa City"; note="Iowa's steady markets and approachable price points suit investors focused on cash flow." }
  @{ slug="kansas"; name="Kansas"; abbr="KS"; metros="Wichita, Overland Park, Kansas City, Topeka, Olathe"; note="Kansas City-area suburbs and Wichita offer a range of price points for rentals and renovation projects." }
  @{ slug="kentucky"; name="Kentucky"; abbr="KY"; metros="Louisville, Lexington, Bowling Green, Covington"; note="Kentucky's metros offer moderate prices and steady rental demand for buy-and-hold investors." }
  @{ slug="louisiana"; name="Louisiana"; abbr="LA"; metros="New Orleans, Baton Rouge, Lafayette, Shreveport"; note="Louisiana investors should look closely at insurance costs, which can be a big factor in how a rental performs." }
  @{ slug="maine"; name="Maine"; abbr="ME"; metros="Portland, Bangor, Lewiston, Augusta"; note="Maine combines year-round rental demand in Portland with seasonal and vacation markets along the coast." }
  @{ slug="maryland"; name="Maryland"; abbr="MD"; metros="Baltimore, Frederick, Rockville, Annapolis"; note="Maryland combines Baltimore-area investment properties with the Washington, D.C. suburbs. Availability and terms can vary by property and area, so we confirm each deal individually." }
  @{ slug="massachusetts"; name="Massachusetts"; abbr="MA"; metros="Boston, Worcester, Springfield, Lowell, Cambridge"; note="Massachusetts has a large stock of 2-4 unit multifamily buildings, popular with investors and house-hackers alike." }
  @{ slug="michigan"; name="Michigan"; abbr="MI"; metros="Detroit, Grand Rapids, Lansing, Ann Arbor, Flint"; note="Michigan has long attracted cash-flow investors, with modest prices and strong rents in many markets." }
  @{ slug="minnesota"; name="Minnesota"; abbr="MN"; metros="Minneapolis, St. Paul, Rochester, Duluth"; note="The Twin Cities anchor Minnesota's rental market, with steady demand and a mix of single-family and small multifamily properties." }
  @{ slug="mississippi"; name="Mississippi"; abbr="MS"; metros="Jackson, Gulfport, Southaven, Hattiesburg"; note="Mississippi offers low price points that can produce strong rent-to-price ratios, with each deal reviewed individually." }
  @{ slug="missouri"; name="Missouri"; abbr="MO"; metros="St. Louis, Kansas City, Springfield, Columbia"; note="Missouri's two large metros give investors a range of rental and renovation opportunities at approachable prices." }
  @{ slug="montana"; name="Montana"; abbr="MT"; metros="Billings, Missoula, Bozeman, Great Falls"; note="Montana's growth markets, such as Bozeman and Missoula, have drawn investors, with each property reviewed on its own merits." }
  @{ slug="nebraska"; name="Nebraska"; abbr="NE"; metros="Omaha, Lincoln, Bellevue, Grand Island"; note="Omaha and Lincoln offer steady rental demand and moderate prices for buy-and-hold investors." }
  @{ slug="nevada"; name="Nevada"; abbr="NV"; metros="Las Vegas, Henderson, Reno"; note="Nevada." }
  @{ slug="new-hampshire"; name="New Hampshire"; abbr="NH"; metros="Manchester, Nashua, Concord, Portsmouth"; note="New Hampshire's southern tier connects to the Boston market and supports steady rental demand." }
  @{ slug="new-jersey"; name="New Jersey"; abbr="NJ"; metros="Newark, Jersey City, Trenton, Camden, Atlantic City"; note="New Jersey's higher property values and strong demand for 2-4 unit properties make careful numbers especially important for both rentals and flips." }
  @{ slug="new-mexico"; name="New Mexico"; abbr="NM"; metros="Albuquerque, Santa Fe, Las Cruces, Rio Rancho"; note="New Mexico's main metros offer approachable price points for rentals and renovation projects." }
  @{ slug="new-york"; name="New York"; abbr="NY"; metros="New York City, Buffalo, Rochester, Syracuse, Albany"; note="New York spans everything from five-borough multifamily to upstate cash-flow markets. Terms vary widely by property and location." }
  @{ slug="north-carolina"; name="North Carolina"; abbr="NC"; metros="Charlotte, Raleigh, Greensboro, Durham, Wilmington, Asheville"; note="Population growth in the Carolinas has kept rental demand strong in Charlotte, the Triangle and coastal markets, creating opportunities for both buy-and-hold investors and flippers." }
  @{ slug="north-dakota"; name="North Dakota"; abbr="ND"; metros="Fargo, Bismarck, Grand Forks"; note="North Dakota." }
  @{ slug="ohio"; name="Ohio"; abbr="OH"; metros="Columbus, Cleveland, Cincinnati, Dayton, Toledo"; note="Ohio is a long-time favorite for cash-flow-focused investors, where purchase prices are modest relative to rents in many neighborhoods." }
  @{ slug="oklahoma"; name="Oklahoma"; abbr="OK"; metros="Oklahoma City, Tulsa, Norman, Broken Arrow"; note="Oklahoma's two big metros offer moderate prices and solid rent-to-price ratios for rental investors." }
  @{ slug="oregon"; name="Oregon"; abbr="OR"; metros="Portland, Salem, Eugene, Bend, Medford"; note="Oregon's metros combine strong rental demand with higher prices, so running the full payment is important." }
  @{ slug="pennsylvania"; name="Pennsylvania"; abbr="PA"; metros="Philadelphia, Pittsburgh, Allentown, Harrisburg, Reading, Scranton"; note="Pennsylvania has a deep supply of older single-family homes and small multifamily buildings, which makes for plenty of renovation and rental opportunities." }
  @{ slug="rhode-island"; name="Rhode Island"; abbr="RI"; metros="Providence, Warwick, Cranston, Pawtucket"; note="Rhode Island has plenty of older multifamily buildings, which makes for rental and renovation opportunities." }
  @{ slug="south-carolina"; name="South Carolina"; abbr="SC"; metros="Charleston, Greenville, Columbia, Myrtle Beach"; note="From the Lowcountry to the Upstate, South Carolina combines coastal vacation-rental activity with growing inland rental markets." }
  @{ slug="south-dakota"; name="South Dakota"; abbr="SD"; metros="Sioux Falls, Rapid City"; note="South Dakota." }
  @{ slug="tennessee"; name="Tennessee"; abbr="TN"; metros="Nashville, Memphis, Knoxville, Chattanooga"; note="Tennessee's metros attract both cash-flow investors and flippers, with a mix of price points from Memphis single-family rentals to Nashville renovation projects." }
  @{ slug="texas"; name="Texas"; abbr="TX"; metros="Houston, Dallas-Fort Worth, San Antonio, Austin, El Paso"; note="Texas investors benefit from a large, growing rental market. Property taxes are higher than in many states, so it is worth running the full payment - taxes and insurance included - before assuming a rental will qualify." }
  @{ slug="utah"; name="Utah"; abbr="UT"; metros="Salt Lake City, Provo, Ogden, St. George, Lehi"; note="Utah's Wasatch Front has seen strong growth and consistent demand for both rental and renovated homes." }
  @{ slug="vermont"; name="Vermont"; abbr="VT"; metros="Burlington, Rutland, Montpelier, Essex"; note="Vermont is a smaller market where each investment property is reviewed individually." }
  @{ slug="virginia"; name="Virginia"; abbr="VA"; metros="Richmond, Virginia Beach, Norfolk, Arlington, Roanoke"; note="Virginia pairs the Northern Virginia and Hampton Roads markets with Richmond and the Shenandoah region." }
  @{ slug="washington"; name="Washington"; abbr="WA"; metros="Seattle, Spokane, Tacoma, Vancouver, Bellevue"; note="Washington's Puget Sound and Spokane markets offer strong rent demand, with higher prices that make precise numbers important." }
  @{ slug="west-virginia"; name="West Virginia"; abbr="WV"; metros="Charleston, Huntington, Morgantown, Parkersburg"; note="West Virginia offers very low price points; each property is reviewed individually." }
  @{ slug="wisconsin"; name="Wisconsin"; abbr="WI"; metros="Milwaukee, Madison, Green Bay, Kenosha, Racine"; note="Milwaukee and Madison give Wisconsin investors steady rental demand, with many 2-4 unit properties." }
  @{ slug="wyoming"; name="Wyoming"; abbr="WY"; metros="Cheyenne, Casper, Laramie, Gillette"; note="Wyoming is a small market where each investment property is reviewed on its own merits." }
)
